---
site_name: moPepGen
docs_dir: docs/
repo_url: https://github.com/zhuchcn/package-moPepGen
site_author: Chenghao Zhu
nav:
  - Home: index.md
  - moPepGen Basics: basics.md
  - Quick Start: quick-start.md
  - Vignette: vignette.md
  - File Format: file-format.md
  - Commands:
      - generateIndex: generate-index.md
      - updateIndex: update-index.md
      - parseVEP: parse-vep.md
      - parseREDItools: parse-reditools.md
      - parseSTARFusion: parse-star-fusion.md
      - parseFusionCatcher: parse-fusion-catcher.md
      - parseArriba: parse-arriba.md
      - parseRMATS: parse-rmats.md
      - parseCIRCexplorer: parse-circexplorer.md
      - callVariant: call-variant.md
      - callNovelORF: call-novel-orf.md
      - callAltTranslation: call-alt-translation.md
      - filterFasta: filter-fasta.md
      - splitFasta: split-fasta.md
      - mergeFasta: merge-fasta.md
      - encodeFasta: encode-fasta.md
      - decoyFasta: decoy-fasta.md
      - summarizeFasta: summarize-fasta.md
theme: readthedocs
plugins:
  - mkdocstrings:
      handlers:
        python:
          docstring_stype: google
  - macros:
      verbose: true
markdown_extensions:
  - tables
  - admonition
